using System.Diagnostics;
using VellumPdf.Conformance;
using VellumPdf.Conformance.Coverage;
using DocumentConformance = VellumPdf.Document.PdfConformance;
using PreflightConformance = VellumPdf.Conformance.PdfConformance;

namespace VellumPdfShowcase.Web.Generation;

/// <summary>
/// The outcome of one preflight run over bytes this site generated.
/// </summary>
/// <param name="Profile">The profile the bytes were validated against.</param>
/// <param name="Result">The library's own result, or <see langword="null"/> when validation itself failed.</param>
/// <param name="ElapsedMilliseconds">Wall clock for the validation call alone.</param>
/// <param name="Error">
/// A legible message when the validator refused the bytes outright, rather than
/// reporting assertions about them. The two are different outcomes and the site
/// must not present them as the same one.
/// </param>
public sealed record PreflightReport(
    PreflightConformance Profile,
    PreflightResult? Result,
    long ElapsedMilliseconds,
    string? Error)
{
    /// <summary>Whether the run produced a verdict at all.</summary>
    public bool Completed => Result is not null;

    /// <summary>Whether the bytes satisfy the profile. Meaningless unless <see cref="Completed"/>.</summary>
    public bool IsCompliant => Result?.IsCompliant ?? false;

    /// <summary>The assertions raised, empty when none were or when the run failed.</summary>
    public IReadOnlyList<PreflightAssertion> Assertions => Result?.Assertions ?? [];
}

/// <summary>
/// Runs <c>PdfPreflight</c> over generated bytes and reports the result in a
/// shape a page can render.
/// </summary>
/// <remarks>
/// NOTE on what this is and is not, because the distinction is the whole reason
/// this type exists rather than the call being made inline. The rule engine here
/// is <c>VellumPdf.Conformance</c>, running in the visitor's own browser. It is
/// NOT veraPDF, and nothing on this site may imply that veraPDF is executing.
/// What may be said about the engine, because the library records it and its own
/// continuous integration enforces it, concerns the engine's provenance rather
/// than any particular run. Keep the two apart wherever this report is displayed.
///
/// NOTE also that validation can fail rather than return a verdict. A validator
/// that throws on bytes this site produced is a finding in itself, so the failure
/// is carried in <see cref="PreflightReport.Error"/> and displayed, rather than
/// being swallowed into a non-compliant verdict that would misattribute it to the
/// document.
/// </remarks>
public static class PreflightRunner
{
    /// <summary>
    /// Validates <paramref name="bytes"/> against the profile the specification
    /// claimed.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="bytes"/> is null.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <paramref name="claimed"/> is <see cref="DocumentConformance.None"/>, which
    /// names no profile to validate against. A caller must decide what to do about
    /// a document claiming nothing; this type will not decide it for them.
    /// </exception>
    public static PreflightReport Run(byte[] bytes, DocumentConformance claimed)
    {
        ArgumentNullException.ThrowIfNull(bytes);

        // ToPreflightProfile returns null for None, which is the only member that
        // names no profile. Reading the null rather than testing the member keeps
        // the two enumerations from being compared anywhere but in the mapping.
        var profile = ConformanceMapping.ToPreflightProfile(claimed)
            ?? throw new ArgumentOutOfRangeException(
                nameof(claimed),
                "A document that claims no conformance profile cannot be preflighted against one.");

        return Run(bytes, profile);
    }

    /// <summary>
    /// Validates <paramref name="bytes"/> against an explicitly chosen profile,
    /// which need not be the one the document claims. The compliance page offers
    /// exactly that, so a visitor can see how a document fares against a profile
    /// it was not built for.
    /// </summary>
    public static PreflightReport Run(byte[] bytes, PreflightConformance profile)
    {
        ArgumentNullException.ThrowIfNull(bytes);

        var stopwatch = Stopwatch.StartNew();

        try
        {
            var result = PdfPreflight.Validate(bytes, profile);
            stopwatch.Stop();
            return new PreflightReport(profile, result, stopwatch.ElapsedMilliseconds, Error: null);
        }
        // The set of types is derived from running the validator over malformed
        // input rather than from reading its signature: bytes that are not a PDF
        // reach it as InvalidDataException from the reader's cross-reference
        // parser, which is NOT an IOException and would otherwise escape. Item 4
        // of the security checklist requires a malformed asset to surface as a
        // legible message, so a type missing from this list is a defect.
        catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or NotSupportedException or IOException or InvalidDataException)
        {
            stopwatch.Stop();
            return new PreflightReport(
                profile,
                Result: null,
                stopwatch.ElapsedMilliseconds,
                $"The validator could not read these bytes: {ex.Message}");
        }
    }

    /// <summary>
    /// The rule coverage the engine declares for a profile, which is a statement
    /// about the engine and not about any document.
    /// </summary>
    public static CoverageSummary Coverage(PreflightConformance profile) => ConformanceCatalog.Coverage(profile);

    /// <summary>The individual checks behind <see cref="Coverage"/>, for the matrix.</summary>
    /// <remarks>
    /// Materialised here rather than passed through as a sequence, because the
    /// matrix is rendered more than once per page and a deferred query would be
    /// re-enumerated each time.
    /// </remarks>
    public static IReadOnlyList<ConformanceCheck> Checks(PreflightConformance profile) => [.. ConformanceCatalog.For(profile)];

    /// <summary>The profiles a visitor may select, in the order the catalogue presents them.</summary>
    public static IReadOnlyList<PreflightConformance> SelectableProfiles { get; } =
    [
        PreflightConformance.PdfA2B,
        PreflightConformance.PdfA2U,
        PreflightConformance.PdfA2A,
        PreflightConformance.PdfUA1,
    ];
}
