using System.Diagnostics;
using Microsoft.JSInterop;
using VellumPdf.Conformance;
using VellumPdf.Layout;
using VellumPdf.Layout.Core;
using VellumPdf.Layout.Elements;
using VellumPdf.Layout.Elements.Table;
using DocumentConformance = VellumPdf.Document.PdfConformance;
using PreflightConformance = VellumPdf.Conformance.PdfConformance;

namespace VellumPdfShowcase.Web.Pages;

public partial class Smoke
{
    // VellumPdf.Layout keeps the underlying PdfDocument private, so a PDF/A
    // claim can only be honoured with a fully embedded face. Document.Conformance
    // (VellumPdf.Document.PdfConformance) and PdfPreflight.Validate
    // (VellumPdf.Conformance.PdfConformance) are two distinct enum types with
    // no conversion between them; both are referenced explicitly below.
    private const string LiberationSansPath = "fonts/LiberationSans-Regular.ttf";

    private IJSObjectReference? _module;
    private byte[]? _fontBytes;

    private bool _busyHardCoded;
    private byte[]? _hardCodedBytes;
    private string? _hardCodedBlobUrl;
    private bool _hardCodedSupportsInline = true;
    private long _hardCodedElapsedMs;

    private bool _busyPdfA;
    private byte[]? _pdfABytes;
    private string? _pdfABlobUrl;
    private bool _pdfASupportsInline = true;
    private long _pdfAGenerationElapsedMs;
    private long _preflightElapsedMs;
    private PreflightResult? _preflightResult;

    private async Task<IJSObjectReference> GetModuleAsync() =>
        _module ??= await JS.InvokeAsync<IJSObjectReference>("import", "./js/pdfInterop.js");

    private async Task GenerateHardCodedAsync()
    {
        _busyHardCoded = true;
        StateHasChanged();
        await Task.Delay(1);

        var stopwatch = Stopwatch.StartNew();
        var bytes = BuildHardCodedDocument();
        stopwatch.Stop();

        _hardCodedBytes = bytes;
        _hardCodedElapsedMs = stopwatch.ElapsedMilliseconds;

        var module = await GetModuleAsync();
        _hardCodedSupportsInline = await module.InvokeAsync<bool>("supportsInlinePdf");

        var previousUrl = _hardCodedBlobUrl;
        var streamRef = new DotNetStreamReference(new MemoryStream(bytes));
        _hardCodedBlobUrl = await module.InvokeAsync<string>("createBlobUrl", streamRef, "application/pdf");

        if (previousUrl is not null)
        {
            await module.InvokeVoidAsync("revokeBlobUrl", previousUrl);
        }

        _busyHardCoded = false;
    }

    private async Task GeneratePdfAAsync()
    {
        _busyPdfA = true;
        StateHasChanged();
        await Task.Delay(1);

        _fontBytes ??= await Http.GetByteArrayAsync(LiberationSansPath);

        var generationStopwatch = Stopwatch.StartNew();
        var bytes = BuildPdfA2BDocument(_fontBytes);
        generationStopwatch.Stop();
        _pdfAGenerationElapsedMs = generationStopwatch.ElapsedMilliseconds;
        _pdfABytes = bytes;

        var preflightStopwatch = Stopwatch.StartNew();
        _preflightResult = PdfPreflight.Validate(bytes, PreflightConformance.PdfA2B);
        preflightStopwatch.Stop();
        _preflightElapsedMs = preflightStopwatch.ElapsedMilliseconds;

        var module = await GetModuleAsync();
        _pdfASupportsInline = await module.InvokeAsync<bool>("supportsInlinePdf");

        var previousUrl = _pdfABlobUrl;
        var streamRef = new DotNetStreamReference(new MemoryStream(bytes));
        _pdfABlobUrl = await module.InvokeAsync<string>("createBlobUrl", streamRef, "application/pdf");

        if (previousUrl is not null)
        {
            await module.InvokeVoidAsync("revokeBlobUrl", previousUrl);
        }

        _busyPdfA = false;
    }

    private async Task DownloadAsync(byte[]? bytes, string fileName)
    {
        if (bytes is null)
        {
            return;
        }

        var module = await GetModuleAsync();
        var streamRef = new DotNetStreamReference(new MemoryStream(bytes));
        await module.InvokeVoidAsync("downloadBytes", streamRef, fileName);
    }

    private static byte[] BuildHardCodedDocument()
    {
        using var document = new Document();

        document.Add(new Heading("VellumPdf Showcase Runtime Test") { Level = 1 });
        document.Add(new Paragraph(
            "This document was generated by VellumPdf.Layout, running inside a WebAssembly module in this browser tab. No server received this request."));

        var table = new TableElement();
        var header = table.AddHeaderRow();
        header.AddCell("Element");
        header.AddCell("Source type");

        AddCapabilityRow(table, "Heading", "VellumPdf.Layout.Elements.Heading");
        AddCapabilityRow(table, "Paragraph", "VellumPdf.Layout.Elements.Paragraph");
        AddCapabilityRow(table, "Table", "VellumPdf.Layout.Elements.Table.TableElement");
        AddCapabilityRow(table, "Pie chart", "VellumPdf.Layout.Elements.PieChart");

        document.Add(table);

        document.Add(new PieChart
        {
            Diameter = 140,
            StartAngle = 0,
            Clockwise = true,
            AltText = "A pie chart with two slices: three quarters rendered, one quarter pending.",
            Slices =
            [
                new PieSlice(75, new ColorRgb(0.11, 0.35, 0.62), "Rendered"),
                new PieSlice(25, new ColorRgb(0.78, 0.78, 0.78), "Pending"),
            ],
        });

        document.SetFooter("Page {page} of {pages}");

        using var stream = new MemoryStream();
        document.Save(stream);
        return stream.ToArray();
    }

    private static void AddCapabilityRow(TableElement table, string element, string source)
    {
        var row = table.AddRow();
        row.AddCell(element);
        row.AddCell(source);
    }

    private static byte[] BuildPdfA2BDocument(byte[] fontBytes)
    {
        using var document = new Document
        {
            Conformance = DocumentConformance.PdfA2b,
            Tagged = true,
            Language = "en",
        };

        var fontHandle = document.UseTrueTypeFont(fontBytes);
        var headingStyle = new TextStyle { FontRef = fontHandle, FontSize = 18 };
        var bodyStyle = new TextStyle { FontRef = fontHandle, FontSize = 11 };
        document.SetDefaultFont(bodyStyle);

        document.Add(new Heading("PDF/A-2b Conformance Sample", headingStyle) { Level = 1, Language = "en" });
        document.Add(new Paragraph(
            "This document embeds a Liberation Sans face and declares a CMYK output intent. VellumPdf.Conformance validates the result against the PDF/A-2b profile immediately below, in this browser.",
            bodyStyle));

        document.SetFooter("Page {page} of {pages}", bodyStyle);
        document.UseCmykOutputIntent();

        using var stream = new MemoryStream();
        document.Save(stream);
        return stream.ToArray();
    }

    public async ValueTask DisposeAsync()
    {
        if (_module is null)
        {
            return;
        }

        if (_hardCodedBlobUrl is not null)
        {
            await _module.InvokeVoidAsync("revokeBlobUrl", _hardCodedBlobUrl);
        }

        if (_pdfABlobUrl is not null)
        {
            await _module.InvokeVoidAsync("revokeBlobUrl", _pdfABlobUrl);
        }

        await _module.DisposeAsync();
    }
}
